### ISSUE TITLE
className not populated for custom components

### ISSUE THREAD

**Issue by jedahu** [shadaj/slinky-styled-components#6]
Thank you for Slinky!

I've had trouble using slinky-styled-components with custom components (FunctionalComponent and StatelessComponent). Everything compiles ok, but the styled-components generated class name doesn't show up in the rendered component.

Spelunking through the code...

Slinky defaults to reading from `.__`, and only uses a custom reader if `.__` is undefined.

https://github.com/shadaj/slinky/blob/febaf4d8b7eb81994ed2d8063a0bb881d1203492/core/src/main/scala/slinky/core/DefinitionBase.scala#L145-L150

styled-components writes its generated class name to `.className` (sibling to `.__`), which is ignored by Slinky.

https://github.com/styled-components/styled-components/blob/4b231586207e8e07b0505fd376c8ccf4cbaece53/packages/styled-components/src/models/StyledComponent.js#L157-L170

I've worked around the problem by creating higher priority implicits that read and write to `.___`, ensuring `.__` is undefined, and a custom `className` aware reader is called by DefinitionBase. This works, but I can't help feeling it shouldn't be necessary.

Is there something I've missed?

**Comment by jedahu** [comment]
Yes, there was. Sorted now!

**Comment by shadaj** [comment]
Ah cool! If I may ask, what was the issue? If it's a common-ish issue it might make a helpful addition to the docs! :)

**Comment by jedahu** [comment]
Ignore the actual issue description. I barked up the wrong tree!

However... the `fromPropsFunction` implicit on `InterpolationPart` unconditionally reads from `.__`.  Which means it fails for components whose reader doesn't write to `.__`. Creating a higher priority implicit worked for me:

```scala
  implicit def fromPropsFunction[O](fn: P => O)(implicit ev: O => InterpolationPart[P], reader[P]): InterpolationPart[P] = {
    (((o: js.Any) => {
      val props = if (o.asInstanceOf[js.Object].hasOwnProperty("__"))
        o.asInstanceOf[js.Dynamic].__.asInstanceOf[P]
      else
        reader.read(o.asInstanceOf[js.Object])
      fn(props)
    }): js.Function1[js.Any, js.Any]).asInstanceOf[InterpolationPart[P]]
  }
```

**Comment by shadaj** [comment]
Ah, yep that's exactly the solution we need! Would you mind creating a PR with this change?
